name: Php unit tests

on:
    push:
        branches: ["develop"] # Check for pushes on develop since I tend to push edits for .gitignore and similar stuff (ik this is not good practice, but frankly idc)
    pull_request:
        branches: ["master", "develop"]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest

        services:
            mariadb:
                image: mariadb:latest
                env:
                    MARIADB_ROOT_PASSWORD: password
                    MARIADB_DATABASE: app
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mariadb-admin ping -h localhost -ppassword"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.3"
                  extensions: pdo_mysql
                  coverage: none

            - uses: actions/checkout@v5
            - name: Install Dependencies
              run: composer install --no-progress --prefer-dist --no-interaction

            - name: Prepare database
              run: php bin/console doctrine:migrations:migrate --env=test

            - name: Execute tests (Unit and Feature tests) via PHPUnit
              run: vendor/bin/phpunit
